<?php

namespace ContainerS1fCgB9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LRT1NTBService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.lRT1NTB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lRT1NTB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'order' => ['privates', '.errored..service_locator.lRT1NTB.App\\Entity\\OrderUser', NULL, 'Cannot autowire service ".service_locator.lRT1NTB": it needs an instance of "App\\Entity\\OrderUser" but this type has been excluded in "config/services.yaml".'],
            'orderStateRepository' => ['privates', 'App\\Repository\\OrderStateRepository', 'getOrderStateRepositoryService', true],
        ], [
            'order' => 'App\\Entity\\OrderUser',
            'orderStateRepository' => 'App\\Repository\\OrderStateRepository',
        ]);
    }
}
