<?php

namespace ContainerS1fCgB9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWayRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\WayRepository' shared autowired service.
     *
     * @return \App\Repository\WayRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\WayRepository'] = new \App\Repository\WayRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
