version: '3.8'
services:
  apache:
    container_name: apache
    build:
      context: ./docker
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html/
      - ./docker/apache.conf:/etc/apache2/sites-available/000-default.conf
