<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS1fCgB9\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS1fCgB9/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerS1fCgB9.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerS1fCgB9\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerS1fCgB9\App_KernelProdContainer([
    'container.build_hash' => 'S1fCgB9',
    'container.build_id' => 'a358f0d5',
    'container.build_time' => 1710781569,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS1fCgB9');
