<?php

namespace ContainerS1fCgB9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XrLcMwIService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.xrLcMwI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xrLcMwI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'PDFService' => ['privates', 'App\\Service\\PDFService', 'getPDFServiceService', true],
            'order' => ['privates', '.errored..service_locator.xrLcMwI.App\\Entity\\OrderUser', NULL, 'Cannot autowire service ".service_locator.xrLcMwI": it needs an instance of "App\\Entity\\OrderUser" but this type has been excluded in "config/services.yaml".'],
        ], [
            'PDFService' => 'App\\Service\\PDFService',
            'order' => 'App\\Entity\\OrderUser',
        ]);
    }
}
