<?php

namespace ContainerS1fCgB9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPDFServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\PDFService' shared autowired service.
     *
     * @return \App\Service\PDFService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\PDFService'] = new \App\Service\PDFService();
    }
}
