<?php

namespace Container48zxgmB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\API\\LoginAPIController::login' => ['privates', '.service_locator.iDorLiY', 'get_ServiceLocator_IDorLiYService', true],
            'App\\Controller\\API\\ProductAPIController::categoriesProducts' => ['privates', '.service_locator.tK5vR04', 'get_ServiceLocator_TK5vR04Service', true],
            'App\\Controller\\API\\ProductAPIController::findProductByRef' => ['privates', '.service_locator.tK5vR04', 'get_ServiceLocator_TK5vR04Service', true],
            'App\\Controller\\Client\\CartController::addProductCart' => ['privates', '.service_locator.IxD9RLm', 'get_ServiceLocator_IxD9RLmService', true],
            'App\\Controller\\Client\\CartController::deliveryChoice' => ['privates', '.service_locator.M8GYPKu', 'get_ServiceLocator_M8GYPKuService', true],
            'App\\Controller\\Client\\CartController::placeOrder' => ['privates', '.service_locator.Wk3QxYu', 'get_ServiceLocator_Wk3QxYuService', true],
            'App\\Controller\\Client\\CartController::viewCart' => ['privates', '.service_locator.IxD9RLm', 'get_ServiceLocator_IxD9RLmService', true],
            'App\\Controller\\Client\\CategoryController::viewAllCategories' => ['privates', '.service_locator.HijfGQu', 'get_ServiceLocator_HijfGQuService', true],
            'App\\Controller\\Client\\CategoryController::viewCategory' => ['privates', '.service_locator.HijfGQu', 'get_ServiceLocator_HijfGQuService', true],
            'App\\Controller\\Client\\HomeController::home' => ['privates', '.service_locator.HijfGQu', 'get_ServiceLocator_HijfGQuService', true],
            'App\\Controller\\Client\\ProductController::viewProduct' => ['privates', '.service_locator.DZowHzb', 'get_ServiceLocator_DZowHzbService', true],
            'App\\Controller\\Client\\ProfilController::getConfirmOrder' => ['privates', '.service_locator.xrLcMwI', 'get_ServiceLocator_XrLcMwIService', true],
            'App\\Controller\\Client\\ProfilController::getOrder' => ['privates', '.service_locator.lRT1NTB', 'get_ServiceLocator_LRT1NTBService', true],
            'App\\Controller\\Client\\RegistrationController::register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\Logistics\\DashboardController::index' => ['privates', '.service_locator.IXjybPV', 'get_ServiceLocator_IXjybPVService', true],
            'App\\Controller\\Logistics\\ProductController::index' => ['privates', '.service_locator.IXjybPV', 'get_ServiceLocator_IXjybPVService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\API\\LoginAPIController:login' => ['privates', '.service_locator.iDorLiY', 'get_ServiceLocator_IDorLiYService', true],
            'App\\Controller\\API\\ProductAPIController:categoriesProducts' => ['privates', '.service_locator.tK5vR04', 'get_ServiceLocator_TK5vR04Service', true],
            'App\\Controller\\API\\ProductAPIController:findProductByRef' => ['privates', '.service_locator.tK5vR04', 'get_ServiceLocator_TK5vR04Service', true],
            'App\\Controller\\Client\\CartController:addProductCart' => ['privates', '.service_locator.IxD9RLm', 'get_ServiceLocator_IxD9RLmService', true],
            'App\\Controller\\Client\\CartController:deliveryChoice' => ['privates', '.service_locator.M8GYPKu', 'get_ServiceLocator_M8GYPKuService', true],
            'App\\Controller\\Client\\CartController:placeOrder' => ['privates', '.service_locator.Wk3QxYu', 'get_ServiceLocator_Wk3QxYuService', true],
            'App\\Controller\\Client\\CartController:viewCart' => ['privates', '.service_locator.IxD9RLm', 'get_ServiceLocator_IxD9RLmService', true],
            'App\\Controller\\Client\\CategoryController:viewAllCategories' => ['privates', '.service_locator.HijfGQu', 'get_ServiceLocator_HijfGQuService', true],
            'App\\Controller\\Client\\CategoryController:viewCategory' => ['privates', '.service_locator.HijfGQu', 'get_ServiceLocator_HijfGQuService', true],
            'App\\Controller\\Client\\HomeController:home' => ['privates', '.service_locator.HijfGQu', 'get_ServiceLocator_HijfGQuService', true],
            'App\\Controller\\Client\\ProductController:viewProduct' => ['privates', '.service_locator.DZowHzb', 'get_ServiceLocator_DZowHzbService', true],
            'App\\Controller\\Client\\ProfilController:getConfirmOrder' => ['privates', '.service_locator.xrLcMwI', 'get_ServiceLocator_XrLcMwIService', true],
            'App\\Controller\\Client\\ProfilController:getOrder' => ['privates', '.service_locator.lRT1NTB', 'get_ServiceLocator_LRT1NTBService', true],
            'App\\Controller\\Client\\RegistrationController:register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\Logistics\\DashboardController:index' => ['privates', '.service_locator.IXjybPV', 'get_ServiceLocator_IXjybPVService', true],
            'App\\Controller\\Logistics\\ProductController:index' => ['privates', '.service_locator.IXjybPV', 'get_ServiceLocator_IXjybPVService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\API\\LoginAPIController::login' => '?',
            'App\\Controller\\API\\ProductAPIController::categoriesProducts' => '?',
            'App\\Controller\\API\\ProductAPIController::findProductByRef' => '?',
            'App\\Controller\\Client\\CartController::addProductCart' => '?',
            'App\\Controller\\Client\\CartController::deliveryChoice' => '?',
            'App\\Controller\\Client\\CartController::placeOrder' => '?',
            'App\\Controller\\Client\\CartController::viewCart' => '?',
            'App\\Controller\\Client\\CategoryController::viewAllCategories' => '?',
            'App\\Controller\\Client\\CategoryController::viewCategory' => '?',
            'App\\Controller\\Client\\HomeController::home' => '?',
            'App\\Controller\\Client\\ProductController::viewProduct' => '?',
            'App\\Controller\\Client\\ProfilController::getConfirmOrder' => '?',
            'App\\Controller\\Client\\ProfilController::getOrder' => '?',
            'App\\Controller\\Client\\RegistrationController::register' => '?',
            'App\\Controller\\Logistics\\DashboardController::index' => '?',
            'App\\Controller\\Logistics\\ProductController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\API\\LoginAPIController:login' => '?',
            'App\\Controller\\API\\ProductAPIController:categoriesProducts' => '?',
            'App\\Controller\\API\\ProductAPIController:findProductByRef' => '?',
            'App\\Controller\\Client\\CartController:addProductCart' => '?',
            'App\\Controller\\Client\\CartController:deliveryChoice' => '?',
            'App\\Controller\\Client\\CartController:placeOrder' => '?',
            'App\\Controller\\Client\\CartController:viewCart' => '?',
            'App\\Controller\\Client\\CategoryController:viewAllCategories' => '?',
            'App\\Controller\\Client\\CategoryController:viewCategory' => '?',
            'App\\Controller\\Client\\HomeController:home' => '?',
            'App\\Controller\\Client\\ProductController:viewProduct' => '?',
            'App\\Controller\\Client\\ProfilController:getConfirmOrder' => '?',
            'App\\Controller\\Client\\ProfilController:getOrder' => '?',
            'App\\Controller\\Client\\RegistrationController:register' => '?',
            'App\\Controller\\Logistics\\DashboardController:index' => '?',
            'App\\Controller\\Logistics\\ProductController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]));
    }
}
