<?php

namespace Container48zxgmB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderUserRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\OrderUserRepository' shared autowired service.
     *
     * @return \App\Repository\OrderUserRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\OrderUserRepository'] = new \App\Repository\OrderUserRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
