<?php

namespace Container48zxgmB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductImgRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ProductImgRepository' shared autowired service.
     *
     * @return \App\Repository\ProductImgRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ProductImgRepository'] = new \App\Repository\ProductImgRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
