<?php

namespace Container48zxgmB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Wk3QxYuService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Wk3QxYu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Wk3QxYu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cartService' => ['privates', 'App\\Service\\CartService', 'getCartServiceService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'orderStateRepository' => ['privates', 'App\\Repository\\OrderStateRepository', 'getOrderStateRepositoryService', true],
            'stockShelfRepository' => ['privates', 'App\\Repository\\StockShelfRepository', 'getStockShelfRepositoryService', true],
            'storeRepository' => ['privates', 'App\\Repository\\StoreRepository', 'getStoreRepositoryService', true],
        ], [
            'cartService' => 'App\\Service\\CartService',
            'entityManager' => '?',
            'orderStateRepository' => 'App\\Repository\\OrderStateRepository',
            'stockShelfRepository' => 'App\\Repository\\StockShelfRepository',
            'storeRepository' => 'App\\Repository\\StoreRepository',
        ]);
    }
}
