<?php

namespace Container48zxgmB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderUser2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.xrLcMwI.App\Entity\OrderUser' shared service.
     *
     * @return \App\Entity\OrderUser
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.xrLcMwI": it needs an instance of "App\\Entity\\OrderUser" but this type has been excluded in "config/services.yaml".');
    }
}
