<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \App\Entity\Product implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'category' => [parent::class, 'category', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'orderDetails' => [parent::class, 'orderDetails', null],
        "\0".parent::class."\0".'productImgs' => [parent::class, 'productImgs', null],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null],
        "\0".parent::class."\0".'stockShelves' => [parent::class, 'stockShelves', null],
        "\0".parent::class."\0".'stockStores' => [parent::class, 'stockStores', null],
        "\0".parent::class."\0".'supplier' => [parent::class, 'supplier', null],
        "\0".parent::class."\0".'unit_price' => [parent::class, 'unit_price', null],
        "\0".parent::class."\0".'weight' => [parent::class, 'weight', null],
        'category' => [parent::class, 'category', null],
        'description' => [parent::class, 'description', null],
        'id' => [parent::class, 'id', null],
        'name' => [parent::class, 'name', null],
        'orderDetails' => [parent::class, 'orderDetails', null],
        'productImgs' => [parent::class, 'productImgs', null],
        'slug' => [parent::class, 'slug', null],
        'stockShelves' => [parent::class, 'stockShelves', null],
        'stockStores' => [parent::class, 'stockStores', null],
        'supplier' => [parent::class, 'supplier', null],
        'unit_price' => [parent::class, 'unit_price', null],
        'weight' => [parent::class, 'weight', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
