<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OrderUser extends \App\Entity\OrderUser implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'city' => [parent::class, 'city', null],
        "\0".parent::class."\0".'date_time' => [parent::class, 'date_time', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'orderDetails' => [parent::class, 'orderDetails', null],
        "\0".parent::class."\0".'orderRanks' => [parent::class, 'orderRanks', null],
        "\0".parent::class."\0".'product_quantity' => [parent::class, 'product_quantity', null],
        "\0".parent::class."\0".'shipping_cost' => [parent::class, 'shipping_cost', null],
        "\0".parent::class."\0".'street' => [parent::class, 'street', null],
        "\0".parent::class."\0".'tax' => [parent::class, 'tax', null],
        "\0".parent::class."\0".'total_price_ht' => [parent::class, 'total_price_ht', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        "\0".parent::class."\0".'zip_code' => [parent::class, 'zip_code', null],
        'city' => [parent::class, 'city', null],
        'date_time' => [parent::class, 'date_time', null],
        'id' => [parent::class, 'id', null],
        'orderDetails' => [parent::class, 'orderDetails', null],
        'orderRanks' => [parent::class, 'orderRanks', null],
        'product_quantity' => [parent::class, 'product_quantity', null],
        'shipping_cost' => [parent::class, 'shipping_cost', null],
        'street' => [parent::class, 'street', null],
        'tax' => [parent::class, 'tax', null],
        'total_price_ht' => [parent::class, 'total_price_ht', null],
        'user' => [parent::class, 'user', null],
        'zip_code' => [parent::class, 'zip_code', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
